### ISSUE TITLE
Story #14 - Add Talk

### ISSUE THREAD

**Issue by Ca-moes** [FEUP-ESOF-2020-21/open-cx-t4g1-grupo-1#26]
## **Story #14**
*As a conference host i want to be able to add a talk to the conference*
#### MockUp
![Home page](https://i.imgur.com/2Mt4vwB.jpg)
#### Acceptance Test
```gherkin
Given I want to add a talk to the conference,
When I press the + floating button,
Then I can fill in the details and add a talk.
```
#### Value
Medium
#### Effort
> To Fill

**Comment by goncaloacteixeira** [comment]
This one is done, just needs connection to database.
