### ISSUE TITLE
Add a User Story - add/remove talks

### ISSUE THREAD

**Issue by goncaloacteixeira** [FEUP-ESOF-2020-21/open-cx-t4g1-grupo-1#8]
A Staff member will want to add/remove a Talk.

Screen for adding talks is already done as in #7 (not storing data as backend is not developed yet).

**Comment by Ca-moes** [comment]
adicionado em https://github.com/FEUP-ESOF-2020-21/open-cx-t4g1-grupo-1/commit/e757b8d3942e797eb97a9d669238b37a61079528
