### ISSUE TITLE
Dealing with Data

### ISSUE THREAD

**Issue by goncaloacteixeira** [FEUP-ESOF-2020-21/open-cx-t4g1-grupo-1#9]
We will want to store and read data from a database. Class "Talk" can be easily serialized manually to JSON.

Some options:
- ~[Firebase Realtime Database](https://firebase.google.com/docs/database) - maybe the best option for json data;~
- [Firebase Firestore](https://firebase.google.com/products/firestore) - Modern and fast but a few headaches are expected;
- ~[Local SQLite DB](https://flutter.dev/docs/cookbook/persistence/sqlite) - Safe option~

**Comment by Ca-moes** [comment]
Objetivo final, app igual á do branch mas a usar dados da base da dados em vez de dados vindos do modelo de dados

Adicionar no fim: Speaker para cada Talk
